In [1]:
import unicodedata
import re
def clean_text(s):
    # bỏ dấu tiếng Việt
    s = unicodedata.normalize('NFD', s)
    s = ''.join(c for c in s if unicodedata.category(c) != 'Mn')
    
    # giữ lại chữ cái
    s = re.sub(r'[^a-zA-Z]', '', s)
    
    return s.lower()

s = "Tổng sản phẩm trong nước (GDP)!!!"
print(clean_text(s))

tongsanphamtrongnuocgdp

In [ ]:
import pandas as pd

file_path = '../../Bronze_Excel_Financial_Report/2018/IS_Thang/02-Bieu-7.2018-1.xlsx'
excel_file = pd.ExcelFile(file_path)

all_sheets = excel_file.sheet_names

import_index = -1
export_index = -1

for i in range(len(all_sheets)):
    name = clean_text(all_sheets[i])
    if any(sheet in name for sheet in ['nk', 'nhapkhau']) and 'quy' not in name and 'gia' not in name:
        import_index = i
    if any(sheet in name for sheet in ['xk', 'xuatkhau']) and 'quy' not in name and 'gia' not in name:
        export_index = i

import_sheet = pd.read_excel(file_path, sheet_name= all_sheets[import_index], header= None)
export_sheet = pd.read_excel(file_path, sheet_name= all_sheets[export_index], header= None)

def extract_ecommerce_data(sheet : pd.DataFrame, type: str):
    # xóa các row không cần thiết
    num_of_remove_row = 0
    for i in range(len(sheet)):
        num_of_remove_row += 1
        if isinstance(sheet.iloc[i, 0], str) and 'mathangchuyeu' in clean_text(sheet.iloc[i, 0]): break

    if type == 'import':
        sheet = sheet.iloc[num_of_remove_row:len(sheet) - 1, ::].reset_index(drop =True)
        
    else: sheet = sheet.iloc[num_of_remove_row::, ::].reset_index(drop =True)

    name_colums = ['product_name', 'luong_thang_truoc', 'gia_tri_thang_truoc', 'luong_thang_nay', 'gia_tri_thang_nay']
    # xoa cac cot kh can thiet
    sheet = sheet.iloc[::, [1, 2, 3, 5 ,6]]
    sheet.columns = name_colums
    if type == 'import': sheet.loc[ 29, 'product_name'] = 'Ô tô-nguyên chiếc' 
    return sheet

In [3]:
df = extract_ecommerce_data(export_sheet, 'e')

In [4]:
df

,product_name,luong_thang_truoc,gia_tri_thang_truoc,luong_thang_nay,gia_tri_thang_nay
0,Thủy sản,NaN,764.041033,NaN,740
1,Rau quả,NaN,326.00348,NaN,330
2,Hạt điều,32.331,293.172854,30,266.737838
3,Cà phê,156.258,296.590486,130,243.958404
4,Chè,11.678,20.428791,12,20.753153
5,Hạt tiêu,22.04,70.541157,22,67.522301
6,Gạo,537.948,281.034695,450,230.266173
7,Sắn và sản phẩm của sắn,169.611,77.813391,150,72.120953
8,Than đá,144.198,20.298252,250,32.346103
9,Dầu thô,313.503,178.816828,444,252
10,Xăng dầu,237.314,158.403323,200,135.573697
11,Hóa chất,NaN,148.705434,NaN,135
12,Sản phẩm hóa chất,NaN,88.247066,NaN,80
13,Sản phẩm từ chất dẻo,NaN,256.894877,NaN,250
14,Cao su,122.261,173.480832,140,188.583228
15,"Túi xách, ví, va li, mũ, ô dù",NaN,290.546979,NaN,300
16,"Sản phẩm mây tre, cói, thảm",NaN,27.943329,NaN,30
17,Gỗ và sản phẩm gỗ,NaN,749.997146,NaN,720
18,"Dệt, may",NaN,2745.418426,NaN,2900
19,Giày dép,NaN,1455.486262,NaN,1400
20,Sản phẩm gốm sứ,NaN,41.533543,NaN,35
21,"Đá quý, KL quý và sản phẩm",NaN,52.370532,NaN,52
22,Sắt thép,452.513,349.625602,450,319.083627
23,"Điện tử, máy tính và LK",NaN,2487.20835,NaN,2300
24,Điện thoại các loại và linh kiện,NaN,3320.394807,NaN,3500
25,"Máy móc, thiết bị, dụng cụ PT khác",NaN,1357.659717,NaN,1100
26,Dây điện và cáp điện,NaN,143.92648,NaN,120
27,Phương tiện vận tải và phụ tùng,NaN,613.09507,NaN,600

In [5]:
# visualing section
import_sheet

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16
0,12. Hàng hóa nhập khẩu,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Nghìn tấn, triệu USD",NaN,NaN,NaN,NaN
3,NaN,NaN,Thực hiện\ntháng 6\nnăm 2018,NaN,NaN,Ước tính\ntháng 7\nnăm 2018,NaN,NaN,Cộng dồn\n7 tháng\nnăm 2018,NaN,NaN,7 tháng năm\n2018 so với cùng\nkỳ năm 2017 (%),NaN,NaN,NaN,NaN,NaN
4,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,Lượng,Trị giá,NaN,Lượng,Trị giá,NaN,Lượng,Trị giá,NaN,Lượng,Trị giá,NaN,utt1,tht1-utt1,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,TỔNG TRỊ GIÁ,NaN,NaN,19045.893971,NaN,NaN,19800,NaN,NaN,130626.069193,NaN,NaN,110.21283,NaN,14700,4345.893971,3.959415
8,NaN,Khu vực kinh tế trong nước,NaN,8094.434575,NaN,NaN,8200,NaN,NaN,54160.477638,NaN,NaN,112.740026,NaN,6200,1894.434575,1.304173
9,NaN,Khu vực có vốn đầu tư NN,NaN,10952,NaN,NaN,11600,NaN,NaN,76465.591555,NaN,NaN,108.490295,NaN,8500,2452,5.916728
10,MẶT HÀNG CHỦ YẾU,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN
11,NaN,Thủy sản,NaN,163.278045,NaN,NaN,140,NaN,NaN,1000.670767,NaN,NaN,129.945888,NaN,120,43.278045,-14.256690
12,NaN,Sữa và sản phẩm sữa,NaN,66.981117,NaN,NaN,80,NaN,NaN,571.965953,NaN,NaN,103.523605,NaN,80,-13.018883,19.436647
13,NaN,Rau quả,NaN,134.388066,NaN,NaN,180,NaN,NaN,915.872486,NaN,NaN,107.265566,NaN,110,24.388066,33.940465
14,NaN,Lúa mỳ,263.957,69.960502,NaN,400,93.888734,NaN,3163.767,751.307802,NaN,103.399999,117.977061,250,54.186328,15.774174,34.202488
15,NaN,Dầu mỡ động thực vật,NaN,69.162559,NaN,NaN,55,NaN,NaN,410.513393,NaN,NaN,100.005207,NaN,75,-5.837441,-20.477205
16,NaN,Thức ăn gia súc và NPL,NaN,372.100315,NaN,NaN,250,NaN,NaN,2232.595283,NaN,NaN,112.270913,,280,92.100315,-32.813817
17,NaN,Xăng dầu,1406.343,958.632299,NaN,1000,690,NaN,8073.702,5351.102924,NaN,107.538294,136.397362,900,510,448.632299,-28.022454
18,NaN,Khí đốt hóa lỏng,156.236,93.398962,NaN,120,72.992297,NaN,855.746,488.377659,NaN,104.781846,124.48073,100,50,43.398962,-21.848920
19,NaN,Sản phẩm khác từ dầu mỏ,NaN,80.133238,NaN,NaN,75,NaN,NaN,568.582662,NaN,NaN,111.167796,NaN,55,25.133238,-6.405879
20,NaN,Hóa chất,NaN,427.140158,NaN,NaN,450,NaN,NaN,2908.706155,NaN,NaN,127.132099,NaN,260,167.140158,5.351836
21,NaN,Sản phẩm hoá chất,NaN,407.422399,NaN,NaN,420,NaN,NaN,2809.633793,NaN,NaN,110.99152,NaN,300,107.422399,3.087116
22,NaN,Tân dược,NaN,216.932887,NaN,NaN,250,NaN,NaN,1609.73306,NaN,NaN,101.080861,NaN,200,16.932887,15.243015
23,NaN,Phân bón,408.28,117.945965,NaN,300,84.153704,NaN,2552.679,727.537932,NaN,85.859488,90.934389,400,106.367603,11.578362,-28.650629
24,NaN,Thuốc trừ sâu,NaN,78.536303,NaN,NaN,90,NaN,NaN,551.77626,NaN,NaN,97.196689,,60,18.536303,14.596685
25,NaN,Chất dẻo,451.661,744.859527,NaN,440,751.670995,NaN,3100.604,5078.086233,NaN,108.728191,118.849724,360,517.820543,227.038984,0.914463
26,NaN,Sản phẩm chất dẻo,NaN,475.279441,NaN,NaN,480,NaN,NaN,3267.702618,NaN,NaN,110.640366,,370,105.279441,0.993218
27,NaN,Cao su,45.868,88.340708,NaN,45,84.741372,NaN,335.082,613.743418,NaN,115.557073,99.008669,45,86.876953,1.463755,-4.074380
28,NaN,Gỗ và sản phẩm gỗ,NaN,191.053576,NaN,NaN,190,NaN,NaN,1259.966127,NaN,NaN,101.994548,,180,11.053576,-0.551456
29,NaN,Giấy các loại,155.398,150.312798,NaN,170,165.487333,NaN,1147.097,1076.34886,NaN,99.276047,112.485767,160,129.730268,20.58253,10.095305
30,NaN,Bông,146.29,278.634541,NaN,165,326.002336,NaN,1001.48,1874.129112,NaN,129.201387,132.628035,100,170,108.634541,16.999972
31,NaN,Sợi dệt,82.83,201.526489,NaN,90,207.782575,NaN,581.789,1361.985905,NaN,117.334019,133.342116,60,128.122367,73.404122,3.104349
32,NaN,Vải,NaN,1137.82149,NaN,NaN,1150,NaN,NaN,7421.193549,NaN,NaN,114.889388,NaN,800,337.82149,1.070336
33,NaN,"Nguyên PL dệt, may, giày dép",NaN,491.775532,NaN,NaN,500,NaN,NaN,3322.65482,NaN,NaN,103.704987,NaN,400,91.775532,1.672403
34,NaN,Sắt thép,1208.864,878.560535,NaN,1250,940.146631,NaN,8129.777,5869.694868,NaN,90.463928,111.633589,1300,710,168.560535,7.009887
35,NaN,Kim loại thường khác,131.918,535.226411,NaN,400,895.563375,NaN,1320.653,4321.702167,NaN,123.153655,126.44758,140,433.128196,102.098215,67.324212
36,NaN,"Điện tử, máy tính và LK",NaN,3166.067545,NaN,NaN,3300,NaN,NaN,23072.362894,NaN,NaN,113.466299,NaN,2250,916.067545,4.230246
37,NaN,Điện thoại các loại và LK,NaN,875.940697,NaN,NaN,900,NaN,NaN,6891.295643,NaN,NaN,92.638312,NaN,850,25.940697,2.746682
38,NaN,"Máy móc thiết bị, DC, PT khác",NaN,2802.605912,NaN,NaN,3000,NaN,NaN,18937.745485,NaN,NaN,93.93856,NaN,2600,202.605912,7.043234
39,NaN,Ô tô,NaN,353.649564,NaN,NaN,504.567064,NaN,NaN,2557.310288,NaN,NaN,82.719637,NaN,444.850214,-91.20065,42.674307
40,NaN,Trong đó: Nguyên chiếc(*),3357,82.169503,NaN,7500,154.567064,NaN,19884,483.84925,NaN,34.391269,40.233048,7,164.850214,-82.680711,88.107580
41,NaN,"Xe máy và linh kiện, phụ tùng",NaN,46.635763,NaN,NaN,55,NaN,NaN,325.934903,NaN,NaN,131.525745,NaN,35,11.635763,17.935242
42,NaN,Phương tiện vận tải khác và PT,NaN,92.329223,NaN,NaN,70,NaN,NaN,507.910684,NaN,NaN,99.282344,NaN,70,22.329223,-24.184351
43,NaN,"(*)Chiếc, triệu USD",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
export_sheet

,0,1,2,3,4,5,6,7,8,9,10,11,12
0,11. Hàng hóa xuất khẩu,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Nghìn tấn, triệu USD"
3,NaN,NaN,Thực hiện\ntháng 6\nnăm 2018,NaN,NaN,Ước tính\ntháng 7\nnăm 2018,NaN,NaN,Cộng dồn\n7 tháng\nnăm 2018,NaN,NaN,7 tháng năm\n2018 so với cùng\nkỳ năm 2017 (%),NaN
4,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,Lượng,Trị giá,NaN,Lượng,Trị giá,NaN,Lượng,Trị giá,NaN,Lượng,Trị giá
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,TỔNG TRỊ GIÁ,NaN,NaN,19845,NaN,NaN,19500,NaN,NaN,133689,NaN,NaN,115.338194
8,NaN,Khu vực kinh tế trong nước,NaN,6024,NaN,NaN,5848,NaN,NaN,39029,NaN,NaN,118.675077
9,NaN,Khu vực có vốn đầu tư NN,NaN,13821,NaN,NaN,13652,NaN,NaN,94660,NaN,NaN,114.016355
10,NaN,Dầu thô,NaN,179,NaN,NaN,252,NaN,NaN,1299,NaN,NaN,74.705342
11,NaN,Hàng hoá khác,NaN,13642,NaN,NaN,13400,NaN,NaN,93361,NaN,NaN,114.857138
12,MẶT HÀNG CHỦ YẾU,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,NaN,Thủy sản,NaN,764.041033,NaN,NaN,740,NaN,NaN,4707.554336,NaN,NaN,108.063215
14,NaN,Rau quả,NaN,326.00348,NaN,NaN,330,NaN,NaN,2318.638329,NaN,NaN,114.614959
15,NaN,Hạt điều,32.331,293.172854,NaN,30,266.737838,NaN,205.078,1964.854845,NaN,109.439138,106.510159
16,NaN,Cà phê,156.258,296.590486,NaN,130,243.958404,NaN,1169.488,2246.924587,NaN,112.215333,95.520801
17,NaN,Chè,11.678,20.428791,NaN,12,20.753153,NaN,68.52,112.020501,NaN,89.567457,93.426095
18,NaN,Hạt tiêu,22.04,70.541157,NaN,22,67.522301,NaN,153.947,520.161823,NaN,104.506174,64.307985
19,NaN,Gạo,537.948,281.034695,NaN,450,230.266173,NaN,3933.331,1998.89404,NaN,114.202845,131.479515
20,NaN,Sắn và sản phẩm của sắn,169.611,77.813391,NaN,150,72.120953,NaN,1624.529,615.131126,NaN,71.470762,108.535587
21,NaN,Than đá,144.198,20.298252,NaN,250,32.346103,NaN,1404.901,186.093491,NaN,119.879054,112.58641
22,NaN,Dầu thô,313.503,178.816828,NaN,444,252,NaN,2324.951,1298.75988,NaN,53.586857,74.705342
23,NaN,Xăng dầu,237.314,158.403323,NaN,200,135.573697,NaN,1800.763,1146.204663,NaN,111.694828,141.149322
24,NaN,Hóa chất,NaN,148.705434,NaN,NaN,135,NaN,NaN,920.532143,NaN,NaN,135.004407
25,NaN,Sản phẩm hóa chất,NaN,88.247066,NaN,NaN,80,NaN,NaN,589.877271,NaN,NaN,120.846439
26,NaN,Sản phẩm từ chất dẻo,NaN,256.894877,NaN,NaN,250,NaN,NaN,1681.576273,NaN,NaN,118.869444
27,NaN,Cao su,122.261,173.480832,NaN,140,188.583228,NaN,704.543,1009.138035,NaN,111.322612,90.311819
28,NaN,"Túi xách, ví, va li, mũ, ô dù",NaN,290.546979,NaN,NaN,300,NaN,NaN,1932.356258,NaN,NaN,99.508832
29,NaN,"Sản phẩm mây tre, cói, thảm",NaN,27.943329,NaN,NaN,30,NaN,NaN,190.70441,NaN,NaN,128.24825
30,NaN,Gỗ và sản phẩm gỗ,NaN,749.997146,NaN,NaN,720,NaN,NaN,4844.459415,NaN,NaN,113.437499
31,NaN,"Dệt, may",NaN,2745.418426,NaN,NaN,2900,NaN,NaN,16541.945526,NaN,NaN,116.180234
32,NaN,Giày dép,NaN,1455.486262,NaN,NaN,1400,NaN,NaN,9092.467431,NaN,NaN,108.942938
33,NaN,Sản phẩm gốm sứ,NaN,41.533543,NaN,NaN,35,NaN,NaN,282.091735,NaN,NaN,109.230555
34,NaN,"Đá quý, KL quý và sản phẩm",NaN,52.370532,NaN,NaN,52,NaN,NaN,343.342092,NaN,NaN,117.725596
35,NaN,Sắt thép,452.513,349.625602,NaN,450,319.083627,NaN,3264.233,2424.173637,NaN,134.597334,149.885723
36,NaN,"Điện tử, máy tính và LK",NaN,2487.20835,NaN,NaN,2300,NaN,NaN,15740.684876,NaN,NaN,114.772018
37,NaN,Điện thoại các loại và linh kiện,NaN,3320.394807,NaN,NaN,3500,NaN,NaN,26117.803291,NaN,NaN,115.767025
38,NaN,"Máy móc, thiết bị, dụng cụ PT khác",NaN,1357.659717,NaN,NaN,1100,NaN,NaN,8984.179344,NaN,NaN,127.113413
39,NaN,Dây điện và cáp điện,NaN,143.92648,NaN,NaN,120,NaN,NaN,906.167655,NaN,NaN,132.925503
40,NaN,Phương tiện vận tải và phụ tùng,NaN,613.09507,NaN,NaN,600,NaN,NaN,4628.31025,NaN,NaN,115.19233